### ISSUE TITLE
Add an option to specify `blockstate` for an IA block

### ISSUE THREAD

**Issue by BredyAK** [ViaVersion/ViaBackwards#972]
### Problem Description

The new option could be located at `items.specific_properties.block.placed_model.blockstate`, and here is an example:

```yaml
items:
  red_block:
    enabled: true
    display_name: red_block-display-name
    resource:
      material: PAPER
      generate: false
      model_id: 2
      model_path: minecraft:item/generated
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: BLOCK
          blockstate: instrument=basedrum,note=1,powered=false # <- New option here!
        drop_when_mined: false
        hardness: 3
        blast_resistance: 3
        break_tools_whitelist:
          - STONE_PICKAXE
          - IRON_PICKAXE
          - DIAMOND_PICKAXE
          - NETHERITE_PICKAXE
        sound:
          break:
            name: minecraft:internal.block.stone.break
            volume: 1.0
            pitch: 0.8
          place:
            name: minecraft:internal.block.stone.place
            volume: 1.0
            pitch: 0.8
          hit:
            name: minecraft:internal.block.stone.hit
            volume: 0.25
            pitch: 0.5
          step:
            name: minecraft:internal.block.stone.step
            volume: 0.15
            pitch: 1.0
          fall:
            name: minecraft:internal.block.stone.fall
            volume: 0.5
            pitch: 0.75
```

Refer to this thread in Discord: [https://discord.com/channels/533407895010803753/1348438925454344243](https://discord.com/channels/533407895010803753/1348438925454344243):

> How to manually set a specific blockstate for an IA item? Because there are some blockstates leave blank in IA for some other usage, and I've read the official doc https://itemsadder.devs.beer/plugin-usage/adding-content/advanced-block-properties/manual-editing-blockstates and it seems that IA only support to merge blockstates, not specify one. And I've also check the cache files, they are messy and not human-readying-friendly. (Blockstates in cache files are represented by numbers)

### Solution Description

See above, to let ItemsAdder handle block models more flexible.
